// Code generated by protoc-gen-go. DO NOT EDIT.
// source: finance.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Processor struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Period               string   `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	Datetime             int64    `protobuf:"varint,3,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	IsFinished           bool     `protobuf:"varint,5,opt,name=isFinished,proto3" json:"isFinished,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Processor) Reset()         { *m = Processor{} }
func (m *Processor) String() string { return proto.CompactTextString(m) }
func (*Processor) ProtoMessage()    {}
func (*Processor) Descriptor() ([]byte, []int) {
	return fileDescriptor_c04e2e1c1ba79a81, []int{0}
}

func (m *Processor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Processor.Unmarshal(m, b)
}
func (m *Processor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Processor.Marshal(b, m, deterministic)
}
func (m *Processor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Processor.Merge(m, src)
}
func (m *Processor) XXX_Size() int {
	return xxx_messageInfo_Processor.Size(m)
}
func (m *Processor) XXX_DiscardUnknown() {
	xxx_messageInfo_Processor.DiscardUnknown(m)
}

var xxx_messageInfo_Processor proto.InternalMessageInfo

func (m *Processor) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Processor) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *Processor) GetDatetime() int64 {
	if m != nil {
		return m.Datetime
	}
	return 0
}

func (m *Processor) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Processor) GetIsFinished() bool {
	if m != nil {
		return m.IsFinished
	}
	return false
}

type Analyzer struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Period               string   `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Analyzer) Reset()         { *m = Analyzer{} }
func (m *Analyzer) String() string { return proto.CompactTextString(m) }
func (*Analyzer) ProtoMessage()    {}
func (*Analyzer) Descriptor() ([]byte, []int) {
	return fileDescriptor_c04e2e1c1ba79a81, []int{1}
}

func (m *Analyzer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Analyzer.Unmarshal(m, b)
}
func (m *Analyzer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Analyzer.Marshal(b, m, deterministic)
}
func (m *Analyzer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Analyzer.Merge(m, src)
}
func (m *Analyzer) XXX_Size() int {
	return xxx_messageInfo_Analyzer.Size(m)
}
func (m *Analyzer) XXX_DiscardUnknown() {
	xxx_messageInfo_Analyzer.DiscardUnknown(m)
}

var xxx_messageInfo_Analyzer proto.InternalMessageInfo

func (m *Analyzer) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Analyzer) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Analyzer) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func init() {
	proto.RegisterType((*Processor)(nil), "protobuf.Processor")
	proto.RegisterType((*Analyzer)(nil), "protobuf.Analyzer")
}

func init() { proto.RegisterFile("finance.proto", fileDescriptor_c04e2e1c1ba79a81) }

var fileDescriptor_c04e2e1c1ba79a81 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xcb, 0xcc, 0x4b,
	0xcc, 0x4b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69,
	0x4a, 0xfd, 0x8c, 0x5c, 0x9c, 0x01, 0x45, 0xf9, 0xc9, 0xa9, 0xc5, 0xc5, 0xf9, 0x45, 0x42, 0x52,
	0x5c, 0x1c, 0xa9, 0x15, 0xc9, 0x19, 0x89, 0x79, 0xe9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x70, 0xbe, 0x90, 0x18, 0x17, 0x5b, 0x41, 0x6a, 0x51, 0x66, 0x7e, 0x8a, 0x04, 0x13, 0x58,
	0x06, 0xca, 0x03, 0xe9, 0x49, 0x49, 0x2c, 0x49, 0x2d, 0xc9, 0xcc, 0x4d, 0x95, 0x60, 0x56, 0x60,
	0xd4, 0x60, 0x0e, 0x82, 0xf3, 0x85, 0x84, 0xb8, 0x58, 0x0a, 0x12, 0x4b, 0x32, 0x24, 0x58, 0xc0,
	0x3a, 0xc0, 0x6c, 0x21, 0x39, 0x2e, 0xae, 0xcc, 0x62, 0xb7, 0xcc, 0xbc, 0xcc, 0xe2, 0x8c, 0xd4,
	0x14, 0x09, 0x56, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x24, 0x11, 0xa5, 0x30, 0x2e, 0x0e, 0xc7, 0xbc,
	0xc4, 0x9c, 0xca, 0xaa, 0x54, 0x82, 0xee, 0x29, 0xae, 0xcc, 0x4d, 0xca, 0xcf, 0x81, 0xb9, 0x07,
	0xc2, 0x43, 0x72, 0x27, 0x33, 0xb2, 0x3b, 0x93, 0xd8, 0xc0, 0x7e, 0x36, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x36, 0x06, 0x9b, 0x6d, 0x0b, 0x01, 0x00, 0x00,
}
