// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inside/inside.proto

package inside

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Processor struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Period               string   `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	StartDatetime        int64    `protobuf:"varint,3,opt,name=startDatetime,proto3" json:"startDatetime,omitempty"`
	EndDatetime          int64    `protobuf:"varint,4,opt,name=endDatetime,proto3" json:"endDatetime,omitempty"`
	Path                 string   `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Processor) Reset()         { *m = Processor{} }
func (m *Processor) String() string { return proto.CompactTextString(m) }
func (*Processor) ProtoMessage()    {}
func (*Processor) Descriptor() ([]byte, []int) {
	return fileDescriptor_inside_15f9d248124cdc13, []int{0}
}
func (m *Processor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Processor.Unmarshal(m, b)
}
func (m *Processor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Processor.Marshal(b, m, deterministic)
}
func (dst *Processor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Processor.Merge(dst, src)
}
func (m *Processor) XXX_Size() int {
	return xxx_messageInfo_Processor.Size(m)
}
func (m *Processor) XXX_DiscardUnknown() {
	xxx_messageInfo_Processor.DiscardUnknown(m)
}

var xxx_messageInfo_Processor proto.InternalMessageInfo

func (m *Processor) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Processor) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *Processor) GetStartDatetime() int64 {
	if m != nil {
		return m.StartDatetime
	}
	return 0
}

func (m *Processor) GetEndDatetime() int64 {
	if m != nil {
		return m.EndDatetime
	}
	return 0
}

func (m *Processor) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Analyzer struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Period               string   `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	Datetime             int64    `protobuf:"varint,4,opt,name=datetime,proto3" json:"datetime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Analyzer) Reset()         { *m = Analyzer{} }
func (m *Analyzer) String() string { return proto.CompactTextString(m) }
func (*Analyzer) ProtoMessage()    {}
func (*Analyzer) Descriptor() ([]byte, []int) {
	return fileDescriptor_inside_15f9d248124cdc13, []int{1}
}
func (m *Analyzer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Analyzer.Unmarshal(m, b)
}
func (m *Analyzer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Analyzer.Marshal(b, m, deterministic)
}
func (dst *Analyzer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Analyzer.Merge(dst, src)
}
func (m *Analyzer) XXX_Size() int {
	return xxx_messageInfo_Analyzer.Size(m)
}
func (m *Analyzer) XXX_DiscardUnknown() {
	xxx_messageInfo_Analyzer.DiscardUnknown(m)
}

var xxx_messageInfo_Analyzer proto.InternalMessageInfo

func (m *Analyzer) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Analyzer) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Analyzer) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *Analyzer) GetDatetime() int64 {
	if m != nil {
		return m.Datetime
	}
	return 0
}

type Chooser struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Period               string   `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	Datetime             int64    `protobuf:"varint,4,opt,name=datetime,proto3" json:"datetime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chooser) Reset()         { *m = Chooser{} }
func (m *Chooser) String() string { return proto.CompactTextString(m) }
func (*Chooser) ProtoMessage()    {}
func (*Chooser) Descriptor() ([]byte, []int) {
	return fileDescriptor_inside_15f9d248124cdc13, []int{2}
}
func (m *Chooser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chooser.Unmarshal(m, b)
}
func (m *Chooser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chooser.Marshal(b, m, deterministic)
}
func (dst *Chooser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chooser.Merge(dst, src)
}
func (m *Chooser) XXX_Size() int {
	return xxx_messageInfo_Chooser.Size(m)
}
func (m *Chooser) XXX_DiscardUnknown() {
	xxx_messageInfo_Chooser.DiscardUnknown(m)
}

var xxx_messageInfo_Chooser proto.InternalMessageInfo

func (m *Chooser) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Chooser) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Chooser) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *Chooser) GetDatetime() int64 {
	if m != nil {
		return m.Datetime
	}
	return 0
}

type Notifier struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Period               string   `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	Datetime             int64    `protobuf:"varint,4,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Strategy             string   `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notifier) Reset()         { *m = Notifier{} }
func (m *Notifier) String() string { return proto.CompactTextString(m) }
func (*Notifier) ProtoMessage()    {}
func (*Notifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_inside_15f9d248124cdc13, []int{3}
}
func (m *Notifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notifier.Unmarshal(m, b)
}
func (m *Notifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notifier.Marshal(b, m, deterministic)
}
func (dst *Notifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notifier.Merge(dst, src)
}
func (m *Notifier) XXX_Size() int {
	return xxx_messageInfo_Notifier.Size(m)
}
func (m *Notifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Notifier.DiscardUnknown(m)
}

var xxx_messageInfo_Notifier proto.InternalMessageInfo

func (m *Notifier) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Notifier) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Notifier) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *Notifier) GetDatetime() int64 {
	if m != nil {
		return m.Datetime
	}
	return 0
}

func (m *Notifier) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func init() {
	proto.RegisterType((*Processor)(nil), "inside.Processor")
	proto.RegisterType((*Analyzer)(nil), "inside.Analyzer")
	proto.RegisterType((*Chooser)(nil), "inside.Chooser")
	proto.RegisterType((*Notifier)(nil), "inside.Notifier")
}

func init() { proto.RegisterFile("inside/inside.proto", fileDescriptor_inside_15f9d248124cdc13) }

var fileDescriptor_inside_15f9d248124cdc13 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x65, 0x52, 0x82, 0x7b, 0x88, 0xc5, 0x48, 0xc8, 0xea, 0x14, 0x45, 0x0c, 0x9d, 0x60,
	0xe0, 0x09, 0x10, 0xcc, 0x08, 0xf5, 0x0d, 0xdc, 0xfa, 0x68, 0x2c, 0x35, 0xbe, 0x60, 0xdf, 0x40,
	0x78, 0x08, 0x5e, 0x80, 0x97, 0x45, 0x38, 0xc1, 0x4a, 0x26, 0xb6, 0x4c, 0xf6, 0x77, 0x77, 0xf2,
	0xff, 0xc9, 0x3a, 0xb8, 0x76, 0x3e, 0x3a, 0x8b, 0xf7, 0xc3, 0x71, 0xd7, 0x05, 0x62, 0x52, 0xe5,
	0x40, 0xf5, 0xb7, 0x80, 0xf5, 0x6b, 0xa0, 0x03, 0xc6, 0x48, 0x41, 0x6d, 0x40, 0xe2, 0xc7, 0xa1,
	0x31, 0xfe, 0x88, 0x5a, 0x54, 0x62, 0xbb, 0xde, 0x65, 0x56, 0x37, 0x50, 0x76, 0x18, 0x1c, 0x59,
	0x7d, 0x96, 0x3a, 0x23, 0xa9, 0x5b, 0xb8, 0x8a, 0x6c, 0x02, 0x3f, 0x1b, 0x46, 0x76, 0x2d, 0xea,
	0xa2, 0x12, 0xdb, 0x62, 0x37, 0x2f, 0xaa, 0x0a, 0x2e, 0xd1, 0xdb, 0x3c, 0xb3, 0x4a, 0x33, 0xd3,
	0x92, 0x52, 0xb0, 0xea, 0x0c, 0x37, 0xfa, 0x3c, 0xbd, 0x9e, 0xee, 0x75, 0x00, 0xf9, 0xe8, 0xcd,
	0xa9, 0xff, 0xc4, 0x7f, 0xdd, 0x62, 0xdf, 0xee, 0xe9, 0xf4, 0xe7, 0x36, 0xd0, 0xc4, 0xb9, 0x98,
	0x39, 0x6f, 0x40, 0xda, 0xb9, 0x4a, 0xe6, 0xfa, 0x1d, 0x2e, 0x9e, 0x1a, 0xa2, 0xb8, 0x60, 0xe4,
	0x97, 0x00, 0xf9, 0x42, 0xec, 0xde, 0xdc, 0x72, 0xa1, 0xbf, 0xbd, 0xc8, 0xc1, 0x30, 0x1e, 0xfb,
	0xf1, 0xcf, 0x33, 0xef, 0xcb, 0xb4, 0x24, 0x0f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x21,
	0x12, 0x1e, 0x3b, 0x02, 0x00, 0x00,
}
