// Code generated by protoc-gen-go. DO NOT EDIT.
// source: porter/porter.proto

package porter

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Object
type Record struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Period               string   `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	Datetime             int64    `protobuf:"varint,4,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Open                 string   `protobuf:"bytes,6,opt,name=open,proto3" json:"open,omitempty"`
	High                 string   `protobuf:"bytes,7,opt,name=high,proto3" json:"high,omitempty"`
	Low                  string   `protobuf:"bytes,8,opt,name=low,proto3" json:"low,omitempty"`
	Close                string   `protobuf:"bytes,9,opt,name=close,proto3" json:"close,omitempty"`
	Volume               int64    `protobuf:"varint,10,opt,name=volume,proto3" json:"volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98f9710046ea7b6, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Record) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Record) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *Record) GetDatetime() int64 {
	if m != nil {
		return m.Datetime
	}
	return 0
}

func (m *Record) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Record) GetOpen() string {
	if m != nil {
		return m.Open
	}
	return ""
}

func (m *Record) GetHigh() string {
	if m != nil {
		return m.High
	}
	return ""
}

func (m *Record) GetLow() string {
	if m != nil {
		return m.Low
	}
	return ""
}

func (m *Record) GetClose() string {
	if m != nil {
		return m.Close
	}
	return ""
}

func (m *Record) GetVolume() int64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

// Request
type GetSymbolRequest struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Period               string   `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSymbolRequest) Reset()         { *m = GetSymbolRequest{} }
func (m *GetSymbolRequest) String() string { return proto.CompactTextString(m) }
func (*GetSymbolRequest) ProtoMessage()    {}
func (*GetSymbolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98f9710046ea7b6, []int{1}
}

func (m *GetSymbolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSymbolRequest.Unmarshal(m, b)
}
func (m *GetSymbolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSymbolRequest.Marshal(b, m, deterministic)
}
func (m *GetSymbolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSymbolRequest.Merge(m, src)
}
func (m *GetSymbolRequest) XXX_Size() int {
	return xxx_messageInfo_GetSymbolRequest.Size(m)
}
func (m *GetSymbolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSymbolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSymbolRequest proto.InternalMessageInfo

func (m *GetSymbolRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *GetSymbolRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetSymbolRequest) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

// Reply
type GetSymbolReply struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetSymbolReply) Reset()         { *m = GetSymbolReply{} }
func (m *GetSymbolReply) String() string { return proto.CompactTextString(m) }
func (*GetSymbolReply) ProtoMessage()    {}
func (*GetSymbolReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98f9710046ea7b6, []int{2}
}

func (m *GetSymbolReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSymbolReply.Unmarshal(m, b)
}
func (m *GetSymbolReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSymbolReply.Marshal(b, m, deterministic)
}
func (m *GetSymbolReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSymbolReply.Merge(m, src)
}
func (m *GetSymbolReply) XXX_Size() int {
	return xxx_messageInfo_GetSymbolReply.Size(m)
}
func (m *GetSymbolReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSymbolReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetSymbolReply proto.InternalMessageInfo

func (m *GetSymbolReply) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "porter.Record")
	proto.RegisterType((*GetSymbolRequest)(nil), "porter.GetSymbolRequest")
	proto.RegisterType((*GetSymbolReply)(nil), "porter.GetSymbolReply")
}

func init() { proto.RegisterFile("porter/porter.proto", fileDescriptor_f98f9710046ea7b6) }

var fileDescriptor_f98f9710046ea7b6 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0x49, 0xd3, 0xa6, 0xed, 0x7e, 0x50, 0xca, 0x7e, 0x52, 0x96, 0xe2, 0xa1, 0xe4, 0x94,
	0x53, 0x97, 0xd6, 0x9b, 0x07, 0xf1, 0xa4, 0x57, 0x89, 0xe0, 0x51, 0x48, 0xdb, 0x21, 0x0d, 0x6c,
	0x32, 0x6b, 0xb2, 0xad, 0x96, 0xd2, 0x8b, 0xe0, 0x0b, 0xe8, 0xa3, 0xf9, 0x0a, 0x1e, 0x7d, 0x08,
	0xd9, 0x9d, 0xa4, 0x88, 0x78, 0xf4, 0x34, 0xff, 0xff, 0x6f, 0xb2, 0x93, 0x99, 0xdd, 0x61, 0xff,
	0x35, 0x96, 0x06, 0x4a, 0x49, 0x61, 0xaa, 0x4b, 0x34, 0xc8, 0x03, 0x72, 0xe3, 0xd3, 0x14, 0x31,
	0x55, 0x20, 0x13, 0x9d, 0xc9, 0xa4, 0x28, 0xd0, 0x24, 0x26, 0xc3, 0xa2, 0xa2, 0xaf, 0xc2, 0x4f,
	0x8f, 0x05, 0x31, 0x2c, 0xb1, 0x5c, 0xf1, 0x31, 0xeb, 0xc1, 0xd3, 0x72, 0x9d, 0x14, 0x29, 0x08,
	0x6f, 0xe2, 0x45, 0xfd, 0xf8, 0xe8, 0xf9, 0x88, 0x05, 0xd5, 0x2e, 0x5f, 0xa0, 0x12, 0x2d, 0x97,
	0xa9, 0x9d, 0xe5, 0x1a, 0xca, 0x0c, 0x57, 0xc2, 0x27, 0x4e, 0xce, 0xd6, 0x5a, 0x25, 0x06, 0x4c,
	0x96, 0x83, 0x68, 0x4f, 0xbc, 0xc8, 0x8f, 0x8f, 0x9e, 0x73, 0xd6, 0x2e, 0x92, 0x1c, 0x44, 0xc7,
	0x9d, 0x70, 0xda, 0x32, 0xd4, 0x50, 0x88, 0x80, 0x98, 0xd5, 0x96, 0xad, 0xb3, 0x74, 0x2d, 0xba,
	0xc4, 0xac, 0xe6, 0x43, 0xe6, 0x2b, 0x7c, 0x14, 0x3d, 0x87, 0xac, 0xe4, 0x27, 0xac, 0xb3, 0x54,
	0x58, 0x81, 0xe8, 0x3b, 0x46, 0xc6, 0xf6, 0xb5, 0x45, 0xb5, 0xc9, 0x41, 0x30, 0xf7, 0xf7, 0xda,
	0x85, 0xf7, 0x6c, 0x78, 0x0d, 0xe6, 0xd6, 0x35, 0x1f, 0xc3, 0xc3, 0x06, 0x2a, 0xf3, 0x97, 0x73,
	0x87, 0xe7, 0x6c, 0xf0, 0xad, 0xbe, 0x56, 0x3b, 0x1e, 0xb1, 0x6e, 0xe9, 0xee, 0xb7, 0x12, 0xde,
	0xc4, 0x8f, 0xfe, 0xcd, 0x07, 0xd3, 0xfa, 0x99, 0xe8, 0xda, 0xe3, 0x26, 0x3d, 0x7f, 0xf5, 0x58,
	0xef, 0xc6, 0xa5, 0xee, 0x66, 0xfc, 0xc5, 0x63, 0xfd, 0x63, 0x25, 0x2e, 0x9a, 0x33, 0x3f, 0x9b,
	0x1f, 0x8f, 0x7e, 0xc9, 0x68, 0xb5, 0x0b, 0xaf, 0x9e, 0xdf, 0x3f, 0xde, 0x5a, 0x97, 0xfc, 0xa2,
	0x5e, 0x0a, 0xb9, 0x9d, 0xc9, 0x66, 0x2a, 0xb9, 0x6f, 0xd4, 0x41, 0xd2, 0x3c, 0x72, 0x4f, 0xf1,
	0x20, 0x69, 0x0e, 0xb9, 0xa7, 0x78, 0x58, 0x04, 0x6e, 0x4d, 0xce, 0xbe, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x87, 0xef, 0x5c, 0xb0, 0x63, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PorterV1Client is the client API for PorterV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PorterV1Client interface {
	GetSymbol(ctx context.Context, in *GetSymbolRequest, opts ...grpc.CallOption) (*GetSymbolReply, error)
}

type porterV1Client struct {
	cc *grpc.ClientConn
}

func NewPorterV1Client(cc *grpc.ClientConn) PorterV1Client {
	return &porterV1Client{cc}
}

func (c *porterV1Client) GetSymbol(ctx context.Context, in *GetSymbolRequest, opts ...grpc.CallOption) (*GetSymbolReply, error) {
	out := new(GetSymbolReply)
	err := c.cc.Invoke(ctx, "/porter.PorterV1/GetSymbol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PorterV1Server is the server API for PorterV1 service.
type PorterV1Server interface {
	GetSymbol(context.Context, *GetSymbolRequest) (*GetSymbolReply, error)
}

func RegisterPorterV1Server(s *grpc.Server, srv PorterV1Server) {
	s.RegisterService(&_PorterV1_serviceDesc, srv)
}

func _PorterV1_GetSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PorterV1Server).GetSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/porter.PorterV1/GetSymbol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PorterV1Server).GetSymbol(ctx, req.(*GetSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PorterV1_serviceDesc = grpc.ServiceDesc{
	ServiceName: "porter.PorterV1",
	HandlerType: (*PorterV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSymbol",
			Handler:    _PorterV1_GetSymbol_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "porter/porter.proto",
}
